default_context:
  project_name: 'basedosdados-website'
  project_slug: 'basedosdados-website'
  domain_main: 'basedosdados.org'
  domain_staging: 'staging.basedosdados.org'
  docker_swarm_stack_name_main: 'basedosdados-org'
  docker_swarm_stack_name_staging: 'staging-basedosdados-org'
  secret_key: 'changethis'
  first_superuser: 'admin@basedosdados.org'
  first_superuser_password: '12345678'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.basedosdados.org", "https://staging.basedosdados.org", "https://basedosdados.org", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@basedosdados.org'
  postgres_password: 'changethis'
  pgadmin_default_user: 'admin@basedosdados.org'
  pgadmin_default_user_password: '12345678'
  traefik_constraint_tag: 'basedosdados.org'
  traefik_constraint_tag_staging: 'staging.basedosdados.org'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:12345678'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
